### ISSUE TITLE
can't dismiss reaction list

### ISSUE THREAD

**Issue by nathanielvirgo** [timhutton/livingphysics#2]
After I add a reaction on level 2 it looks like this:

![image](https://user-images.githubusercontent.com/6964676/69856131-3f235880-12d0-11ea-939e-cf17b7e7e9f0.png)

I can't find a way to close that screen - I guess the button for it is off the edge of the screen?

**Comment by nathanielvirgo** [comment]
this is on Chrome on Mac OS X.

**Comment by timhutton** [comment]
Drag the text upwards using the mouse to reach the buttons at the bottom of the dialog.

Yes, the interface is a bit weird - it made more sense on mobile. It needs fixing.

**Comment by timhutton** [comment]
Added buttons for up and down scrolling, so at least the app is usable if drag-to-scroll isn't discovered.
